# Gnuplot MS-Windows 32 bit version 4.0
# Plots the electron/positron tracks generated by 'pm_field.f'

set size ratio -1

set ticslevel 0.05
set xlabel "X"
set ylabel "Y"
set zlabel "Z"
set view 65,40,1,1
splot 'track' u 1:2:3 w lines 1
pause -1

unset mouse

set xlabel "X"
set ylabel "Y"
plot 'track' u 1:2 w lines 1
pause -1

set xlabel "X"
set ylabel "Z"
plot 'track' u 1:3 w lines 1
pause -1

set xlabel "Y"
set ylabel "Z"
plot 'track' u 2:3 w lines 1
pause -1
